[profile.default]
solc-version = "0.8.10"
libs = ['node_modules']
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin",
]
