[profile.default]
solc-version = "0.8.10"
libs = ['node_modules']
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

remappings = [
    "forge-std/=node_modules/forge-std/src",
    "@openzeppelin/=node_modules/@openzeppelin",
    "@bridge/=node_modules/@aave/governance-crosschain-bridges",
    "@scripts/=scripts/forge"
]
